# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe47dc1ee4cf2d586b98ba62960771b9e1db8d4c7e2af73bfdfb0c7098374cbc9539d051d2c4e59c6913a9fa8acac237e8b2fea65bb432ccd36497d19c9a4990

test:
  secret_key_base: ceb02c5081af7b204724500bdc88d0fa45cd733de1faff2c41d5c78ab6c236c5429ebb7c0009181ad8dd7cd5ef6e543294a4989e84cdaf154021b84de5810085

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
